# Generated by Django 3.1.7 on 2021-03-03 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Банки',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimenovanie', models.CharField(max_length=40)),
                ('adress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Бухгалтерские_счета',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimenovanie', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Виды_хоз_деятельности',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimenovanie', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Налоговые_комитеты',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimenovanie', models.CharField(max_length=40)),
                ('adress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Форма_организации',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimenovanie', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Финансовые_показатели',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rnn', models.CharField(max_length=12)),
                ('kvartal', models.IntegerField()),
                ('year', models.DateField()),
                ('summa', models.IntegerField()),
                ('priznak', models.CharField(max_length=2)),
                ('buh_schet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.бухгалтерские_счета')),
            ],
        ),
        migrations.CreateModel(
            name='Предприятия_виды_деятельности',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rnn', models.CharField(max_length=12)),
                ('vid_hoz_deyatelnosti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.виды_хоз_деятельности')),
            ],
        ),
        migrations.CreateModel(
            name='Предприятия_банки',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rnn', models.CharField(max_length=12)),
                ('licevoy_schet', models.CharField(max_length=20)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.банки')),
            ],
        ),
        migrations.CreateModel(
            name='Предприятие',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rnn', models.CharField(max_length=12)),
                ('naimenovanie_polnoe', models.CharField(max_length=40)),
                ('naimenovanie_sokrashennoe', models.CharField(max_length=10)),
                ('adress', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('fio', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('chislo_rabotnikov', models.IntegerField()),
                ('uchrediteli', models.CharField(max_length=150)),
                ('forma_organizacii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.форма_организации')),
                ('nalog_komitet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.налоговые_комитеты')),
                ('vid_hoz_deyatelnosti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.виды_хоз_деятельности')),
            ],
        ),
    ]
