# Generated by Django 3.1.7 on 2021-04-11 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BS',
            fields=[
                ('kod', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('ТОО', 'Товарищество с ограниченной ответственностью'), ('ИП', 'Индивидуальный предприниматель'), ('ООО', 'Общество с ограниченной ответственностью'), ('АО', 'Акционерное общество'), ('ЗАО', 'Закрытое акционерное общество')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kvartal', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('summa', models.PositiveIntegerField()),
                ('priznak', models.CharField(choices=[('Дт', 'Дебет'), ('Кт', 'Кредит')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NK',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schet', models.CharField(max_length=20, unique=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Predpriyatie',
            fields=[
                ('bin_id', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=50, unique=True)),
                ('sh_name', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=60, unique=True)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('fio_ruk', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('chislo_rab', models.PositiveIntegerField()),
                ('uchrediteli', models.CharField(max_length=200, unique=True)),
                ('form_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.fo')),
                ('nalog_kom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.nk')),
            ],
        ),
        migrations.CreateModel(
            name='PVD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_pvd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.predpriyatie')),
            ],
        ),
        migrations.CreateModel(
            name='VHD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='предприятие',
            name='forma_organizacii',
        ),
        migrations.RemoveField(
            model_name='предприятие',
            name='nalog_komitet',
        ),
        migrations.RemoveField(
            model_name='предприятие',
            name='vid_hoz_deyatelnosti',
        ),
        migrations.RemoveField(
            model_name='предприятия_банки',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='предприятия_виды_деятельности',
            name='vid_hoz_deyatelnosti',
        ),
        migrations.RemoveField(
            model_name='финансовые_показатели',
            name='buh_schet',
        ),
        migrations.DeleteModel(
            name='Банки',
        ),
        migrations.DeleteModel(
            name='Бухгалтерские_счета',
        ),
        migrations.DeleteModel(
            name='Виды_хоз_деятельности',
        ),
        migrations.DeleteModel(
            name='Налоговые_комитеты',
        ),
        migrations.DeleteModel(
            name='Предприятие',
        ),
        migrations.DeleteModel(
            name='Предприятия_банки',
        ),
        migrations.DeleteModel(
            name='Предприятия_виды_деятельности',
        ),
        migrations.DeleteModel(
            name='Финансовые_показатели',
        ),
        migrations.DeleteModel(
            name='Форма_организации',
        ),
        migrations.AddField(
            model_name='pvd',
            name='vid_hoz_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.vhd'),
        ),
        migrations.AddField(
            model_name='predpriyatie',
            name='vid_hoz_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.vhd'),
        ),
        migrations.AddField(
            model_name='pb',
            name='bin_pb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.predpriyatie'),
        ),
        migrations.AddField(
            model_name='fp',
            name='bin_fp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.predpriyatie'),
        ),
        migrations.AddField(
            model_name='fp',
            name='bs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.bs'),
        ),
    ]
